Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 512
      Handler: com.junodx.functions.InsuranceService
      CodeUri: /Users/jonathanmckinney/IdeaProjects/junodx/jdx-insurance-microservice
      Runtime: java11
      Architectures:
        - x86_64